# Étape 1 : Construire l'application avec Node.js
FROM node:18 AS build

# Dossier de travail
WORKDIR /app

# Copier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install --legacy-peer-deps


# Copier tout le projet
COPY . .

# Construire l'application avec Vite
RUN npm run build

# Étape 2 : Utiliser Nginx pour servir l'application
FROM nginx:stable-alpine
RUN rm -rf /usr/share/nginx/html/*
# Copier les fichiers de build Vite dans le dossier Nginx
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Exposer le port 80
EXPOSE 80

# Lancer Nginx
CMD ["nginx", "-g", "daemon off;"]
