

services:
  frontend:
    image: nourben585/frontend-app:latest
    ports:
      - "3000:80"  

  backend:
    image: nourben585/backend-app:latest 
    ports:
      - "8800:8800"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb 
      
     
      
    depends_on:
      - mongo
   


  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:


 
