
services:
  frontend:
    image: nourben585/frontend-app:latest
    networks:
      - webnet
  backend:
    image: nourben585/backend-app:latest 
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb       
    depends_on:
      - mongo
    networks:
      - webnet


  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - webnet

  loadbalancer:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - webnet

volumes:
  mongo-data:


networks:
  webnet:
 
