

services:
  frontend:
    image: ${DOCKER_USERNAME}/client:latest
    ports:
      - "3000:80"  

  backend:
    image: ${DOCKER_USERNAME}/api:latest 
    ports:
      - "8800:8800"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb 
    volumes:
      - ./api/.env:/app/.env
      
    depends_on:
      - mongo
   


  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:


 
