{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.containerPort }}
{{- end }}
