apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platforme-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/nourbenecheikh/plateforme.git'
    targetRevision: fullstack-fiverr
    path: platform-chart       
    helm:
      valueFiles:
        - values/backend-values.yaml    
        - values/frontend-values.yaml   
        - values/mongodb-values.yaml 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default                                             
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  
