name: CI/CD Pipeline for Plateforme

on:
  push:
    branches:
      - fullstack-fiverr

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: pull Docker Image( Frontend)
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/client:latest

      - name: pull Docker Image (Backend)
        run: |
         
          docker pull ${{ secrets.DOCKER_USERNAME }}/api:latest

      - name: run frontend container
        run: |

          docker run -d -p 3000:80 ${{ secrets.DOCKER_USERNAME }}/client:latest
      - name: Run Backend Container
        run: |
          docker run -d -p 8800:8800 ${{ secrets.DOCKER_USERNAME }}/api:latest
