name: ZAP DAST Scan

on:
  workflow_dispatch:
  push:
    branches:
      - Dast-scan

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ZAP Scan in Docker
        run: |
          mkdir zap-reports
          docker run --rm \
            -v ${{ github.workspace }}/zap-reports/results:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy zap-baseline.py \
            -t https://e9d0e882c4c7.ngrok-free.app \
            -J zap_report.json \

      - name: Display ZAP Scan Markdown Report
        run: |
          echo "📋 ZAP Scan Markdown Report:"
          echo "-----------------------------------------"
          cat zap-reports/zap_report.json
