name: ZAP DAST Scan

on:
  workflow_dispatch:
  push:
    branches:
      - Dast-scan

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ZAP Scan for Localhost
        run: | 
          docker run --rm \
            -v $(pwd)/dast-rapport:/zap/wrk:rw \
            --network="host" \
            ghcr.io/zaproxy/zaproxy \
            zap-baseline.py \
            -t http://localhost:3000 \
            -J zap_report.json

      - name: Display ZAP Scan Markdown Report
        run: |
          echo "📋 ZAP Scan Markdown Report:"
          echo "-----------------------------------------"
          cat dast-rapport/zap_report.json
