name: SAST Scan with Semgrep

on:
  push:
    branches:
      - fullstack-fiverr
  pull_request:
    branches:
      - fullstack-fiverr

jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Semgrep for Backend
        run: |
          docker run --rm -v "$PWD/api:/src" returntocorp/semgrep semgrep --config p/default /src
      - name: Upload SARIF results for Backend
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: plateforme/semgrep-results/semgrep-backend.sarif

      - name: Run Semgrep for Frontend
        run: |
          docker run --rm -v "$PWD/client:/src" returntocorp/semgrep semgrep --config p/default /src
      
      - name: Upload SARIF results for Frontend
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: plateforme/semgrep-resultrs/semgrep-frontend.sarif
